version: '3.9'
services:
  db:
    image: mariadb:10.6
    command: --default-authentication-plugin=caching_sha2_password              # =mysql_native_password -- Se añade ante 'mysqli_connect(): The server requested authentication method unknown to the client [caching_sha2_password]' --     command: --default-authentication-plugin=mysql_native_password              # Se añade ante 'mysqli_connect(): The server requested authentication method unknown to the client [caching_sha2_password]'
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: 'ventas'
      MYSQL_ROOT_HOST: '%'
      TZ: 'Europe/Madrid'
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - asir_data:/var/lib/mysql                                             # $ sudo ls -la /var/lib/docker/volumes/proyecto_mysql_data/_data

volumes:
  asir_data: